import { CategoryNode, Product } from './types';

export const CATEGORIES: CategoryNode[] = [
  { name: 'Alimentos y bebidas', icon: '🍎', subcategories: ['Frescos', 'Congelados', 'Secos', 'Enlatados'] },
  { name: 'Farmacia / Salud', icon: '💊' },
  { name: 'Higiene personal', icon: '🧴' },
  { name: 'Limpieza', icon: '🧼' },
  { name: 'Indumentaria', icon: '👕' },
  { name: 'Calzado', icon: '👟' },
  { name: 'Accesorios', icon: '🧢' },
  { name: 'Electrónica', icon: '📱' },
  { name: 'Informática', icon: '💻' },
  { name: 'Electrodomésticos', icon: '🔌' },
  { name: 'Ferretería', icon: '🛠️' },
  { name: 'Construcción', icon: '🏗️' },
  { name: 'Juguetes', icon: '🧸' },
  { name: 'Gaming', icon: '🎮' },
  { name: 'Librería', icon: '📚' },
  { name: 'Mascotas', icon: '🐶' },
  { name: 'Automotor', icon: '🚗' },
  { name: 'Jardinería', icon: '🌱' },
  { name: 'Químicos', icon: '🧪' },
  { name: 'Insumos industriales', icon: '🏭' },
  { name: 'Otros', icon: '📦' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Leche Descremada 1L',
    qrCode: '7790001',
    category: 'Alimentos y bebidas',
    type: 'Frescos',
    brand: 'La Serenísima',
    expiryDate: new Date(Date.now() + 86400000 * 5).toISOString().split('T')[0], // 5 days from now
    stock: 15,
    minStock: 20,
    supplier: 'Mastellone Hnos',
    buyPrice: 1.2,
    sellPrice: 1.8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Ibuprofeno 600mg',
    qrCode: '7790002',
    category: 'Farmacia / Salud',
    type: 'Medicamentos',
    brand: 'Bayer',
    expiryDate: new Date(Date.now() - 86400000).toISOString().split('T')[0], // Expired yesterday
    stock: 50,
    minStock: 10,
    supplier: 'Droguería Sur',
    buyPrice: 5.0,
    sellPrice: 8.5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'MacBook Pro M3',
    qrCode: 'APPLE-M3-001',
    category: 'Informática',
    type: 'Laptops',
    brand: 'Apple',
    expiryDate: null,
    stock: 3,
    minStock: 2,
    supplier: 'Apple Dist.',
    buyPrice: 1800,
    sellPrice: 2400,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Coca Cola 2.25L',
    qrCode: '54490001',
    category: 'Alimentos y bebidas',
    type: 'Bebidas',
    brand: 'Coca Cola',
    expiryDate: new Date(Date.now() + 86400000 * 60).toISOString().split('T')[0],
    stock: 120,
    minStock: 50,
    supplier: 'Femsa',
    buyPrice: 2.0,
    sellPrice: 3.5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
